entries:
- title: sidebar
  product: Fluid-Structure Interaction Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: 2D Mok benchmark
      url: /pages/Applications/Fluid-Structure_Interaction_Application/General/2D-Mok-benchmark.html
      output: web
