entries:
- title: sidebar
  product: Mapping Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: How to do Mapping between nonmatching meshes
      url: /pages/Applications/Mapping_Application/General/How-to-do-Mapping-between-nonmatching-meshes.html
      output: web
