entries:
- title: sidebar
  product: Particle Mechanics Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: Particle Mechanics Application
      url: /pages/Applications/Particle_Mechanics_Application/General/Overview.html
      output: web
  - title: MPM example in GiD
    output: web
    folderitems:
    - title: Introduction
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/introduction.html
      output: web
    - title: Set up of example
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/set_up.html
      output: web
    - title: Meshing
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/meshing.html
      output: web
    - title: Calculation
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/calculation.html
      output: web
    - title: Post processing
      url: /pages/Applications/Particle_Mechanics_Application/MPM_example_in_GiD/post_processing.html
      output: web
  - title: Examples
    output: web
    folderitems:
    - title: Cylinder on inclined plane 2D - comparison between analytical and numerical solution with MPM
      url: /pages/Applications/Particle_Mechanics_Application/Examples/Cylinder_on_inclined_plane.html
      output: web
    - title: Granular Flow 2D Validation Test
      url: /pages/Applications/Particle_Mechanics_Application/Examples/Granular_flow_2d.html
      output: web
    - title: Granular flow 2d readme
      url: /pages/Applications/Particle_Mechanics_Application/Examples/remote_Granular_flow_2d_readme.html
      output: web
