entries:
- title: sidebar
  product: ROM Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: API for RomApplication (draft to be moved elsewhere
      url: /pages/Applications/Reduced_Order_Modelling_Application/General/API-for-RomApplication-(draft-to-be-moved-elsewhere.html
      output: web
    - title: API for RomApplication (draft to be moved elsewhere)
      url: /pages/Applications/Reduced_Order_Modelling_Application/General/API-for-RomApplication-(draft-to-be-moved-elsewhere).html
      output: web
