entries:
- title: sidebar
  product: Statistics Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: Overview
      url: /pages/Applications/Statistics_Application/General/Overview.html
      output: web
  - title: Norm Methods
    output: web
    folderitems:
    - title: Overview
      url: /pages/Applications/Statistics_Application/Norm_Methods/Overview.html
      output: web
    - title: Component Based Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/component_based.html
      output: web
    - title: Euclidean Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/euclidean.html
      output: web
    - title: Frobenius Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/frobenius.html
      output: web
    - title: Index Based Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/index_based.html
      output: web
    - title: Infinity Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/infinity.html
      output: web
    - title: Lpq Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/lpq_norm.html
      output: web
    - title: Magnitude Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/magnitude.html
      output: web
    - title: P Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/p_norm.html
      output: web
    - title: Trace Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/trace.html
      output: web
    - title: Value Norm
      url: /pages/Applications/Statistics_Application/Norm_Methods/value.html
      output: web
  - title: Statistical Methods
    output: web
    folderitems:
    - title: Distribution
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Distribution.html
      output: web
    - title: Max
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Max.html
      output: web
    - title: Mean
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Mean.html
      output: web
    - title: Median
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Median.html
      output: web
    - title: Min
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Min.html
      output: web
    - title: Root Mean Square
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Root_Mean_Square.html
      output: web
    - title: Sum
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Sum.html
      output: web
    - title: Variance
      url: /pages/Applications/Statistics_Application/Statistical_Methods/Variance.html
      output: web
  - title: Domains
    output: web
    folderitems:
    - title: 
      output: web
      subfolders:
      - title: Spatial
        output: web
        subfolderitems:
        - title: Spatial Containers
          url: /pages/Applications/Statistics_Application/Domains/Spatial/spatial_containers.html
          output: web
        - title: Spatial Methods
          url: /pages/Applications/Statistics_Application/Domains/Spatial/spatial_methods.html
          output: web
        - title: Spatial Statistics Process
          url: /pages/Applications/Statistics_Application/Domains/Spatial/spatial_statistics_process.html
          output: web
      - title: Temporal
        output: web
        subfolderitems:
        - title: Temporal Containers
          url: /pages/Applications/Statistics_Application/Domains/Temporal/temporal_containers.html
          output: web
        - title: Temporal Methods
          url: /pages/Applications/Statistics_Application/Domains/Temporal/temporal_methods.html
          output: web
        - title: Temporal Statistics Process
          url: /pages/Applications/Statistics_Application/Domains/Temporal/temporal_statistics_process.html
          output: web
  - title: Examples
    output: web
    folderitems:
    - title: Spatial Process Example
      url: /pages/Applications/Statistics_Application/Examples/spatial_example.html
      output: web
    - title: Temporal Process Example
      url: /pages/Applications/Statistics_Application/Examples/temporal_example.html
      output: web
