entries:
- title: sidebar
  product: Structural Mechanics Application
  output: web
  folders:
  - title: General
    output: web
    folderitems:
    - title: Composite clamped cylinder
      url: /pages/Applications/Structural_Mechanics_Application/General/Composite-clamped-cylinder.html
      output: web
    - title: Composite hinged cylindrical roof snapthrough
      url: /pages/Applications/Structural_Mechanics_Application/General/Composite-hinged-cylindrical-roof-snapthrough.html
      output: web
    - title: Formfinding and Membrane Analysis
      url: /pages/Applications/Structural_Mechanics_Application/General/Formfinding-and-Membrane-Analysis.html
      output: web
    - title: Hinged cylindrical roof snapthrough
      url: /pages/Applications/Structural_Mechanics_Application/General/Hinged-cylindrical-roof-snapthrough.html
      output: web
    - title: KratosStructuralMechanicsAPI Constitutive laws in Structural Mechanics Application
      url: /pages/Applications/Structural_Mechanics_Application/General/KratosStructuralMechanicsAPI-Constitutive-laws-in-Structural-Mechanics-Application.html
      output: web
    - title: Non linear cantilever beam
      url: /pages/Applications/Structural_Mechanics_Application/General/Non-linear-cantilever-beam.html
      output: web
    - title: Open cylinder pull out
      url: /pages/Applications/Structural_Mechanics_Application/General/1_Open-cylinder-pull-out.html
      output: web
    - title: Roll up beam cantilever
      url: /pages/Applications/Structural_Mechanics_Application/General/0_Roll-up-beam-cantilever.html
      output: web
    - title: Shallow angle beam
      url: /pages/Applications/Structural_Mechanics_Application/General/Shallow-angle-beam.html
      output: web
    - title: Shell obstacle course Pinched cylinder
      url: /pages/Applications/Structural_Mechanics_Application/General/Shell-obstacle-course-Pinched-cylinder.html
      output: web
    - title: Shell obstacle course Pinched hemisphere
      url: /pages/Applications/Structural_Mechanics_Application/General/Shell-obstacle-course-Pinched-hemisphere.html
      output: web
    - title: Shell obstacle course Scordelis Lo roof
      url: /pages/Applications/Structural_Mechanics_Application/General/Shell-obstacle-course-Scordelis-Lo-roof.html
      output: web
    - title: Two bar truss   snap through
      url: /pages/Applications/Structural_Mechanics_Application/General/Two-bar-truss---snap-through.html
      output: web
